// Supabase Configuration
// This file is automatically generated when connecting to Supabase project
// Project ID: crwclglcyaifwizcbsat

class SupabaseConfig {
  static const String supabaseUrl = 'https://crwclglcyaifwizcbsat.supabase.co';
  static const String supabaseAnonKey = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNyd2NsZ2xjeWFpZndpemNic2F0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3Njc3MTQyNjQsImV4cCI6MjA4MzI5MDI2NH0.VDB9fEs3fvWVPoYJalx2tjFV5u3apjDRL-cWfKfRhEc';
}
